baseURL = 'https://belphonz.github.io/'
languageCode = 'en-us'
title = "Portfolio - Aethel B. Crown"
theme = 'poison'
paginate = 10
pluralizelisttitles = false



[params]

    brand = "Aethel Bon Crown"
    brand_image = "/assets/profile.png"
    dark_mode = true 
    description = "Student Programmer" 
    favicon = "/assets/favicon.ico"

    menu = [
        {Name = "About Me", HasChildren = false, URL = "/about/"},
        
    ]
    front_page_content = ["education"]
    reading_time = true

    github_url = "https://github.com/Belphonz"
    linkedin_url = "https://www.linkedin.com/in/aethel-crown/"
    twitter_url = "https://x.com/AethelCrown"
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files